name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"   # only run when you push a tag like v0.1.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed app.py --name FWinPhotoViewer-win.exe --icon=assets/icon.ico --add-data "assets/icon.ico;assets"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --windowed --onedir app.py \
            --name FWinPhotoViewer-mac \
            --icon=assets/icon.icns \
            --add-binary "$(python3 -m PyQt6.QtCore.QLibraryInfo --path Plugins)/platforms/libqcocoa.dylib:PyQt6/Qt/plugins/platforms"
            cd dist
            zip -r ../FWinPhotoViewer-mac.zip FWinPhotoViewer-mac.app
          else
            pyinstaller --onefile --windowed app.py --name FWinPhotoViewer-linux --icon=assets/icon.png
          fi
        shell: bash


      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/FWinPhotoViewer-win.exe
            dist/FWinPhotoViewer-linux
            FWinPhotoViewer-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
